version: "3.8"
services:
  api_gateway:
    platform: linux/x86_64
    build: ./app
    image: app
    env_file:
      - ./.env
    ports:
      - "8081:8081"
    command: [ "python3.9", "__main__.py" ]